# MySQL Deployment for CLO835 Final Project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: fp
  labels:
    app: mysql
    project: clo835-final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "clo835_password123"
        - name: MYSQL_DATABASE
          value: "employees"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        # Temporary: Use emptyDir for now to avoid PVC issues
        # volumeMounts:
        # - name: mysql-storage
        #   mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - --password=clo835_password123
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - --password=clo835_password123
            - -e
            - "SELECT 1"
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
      # Temporary: Use emptyDir for now to avoid PVC issues
      # volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc