# MySQL Service for internal database access
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: clo835
  labels:
    app: mysql
    project: clo835-final-project
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql