# PersistentVolumeClaim for MySQL data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: fp
  labels:
    app: mysql
    project: clo835-final-project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 3Gi