# Flask WebApp LoadBalancer Service for external access
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: fp
  labels:
    app: webapp
    project: clo835-final-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
    protocol: TCP
    name: http
  selector:
    app: webapp